### ISSUE TITLE
Curly braces within strings get replaced

### ISSUE THREAD

**Issue by infinnie** [dy/scope-css#5]
JSFiddle: https://jsfiddle.net/cmkLsx25/

```js
scope(":host:before {content:\"{}\"}",".test")
```

Expected result:
```css
.test:before {content:"{}"}
```

Actual result:
```css
.test:before {.test content:"{}"}
```

**Comment by dy** [comment]
Fixed in @1.2.1.

**Comment by infinnie** [comment]
What about actually parsing it?

**Comment by dy** [comment]
Bundle is intended to be small to be used in browser. If you are not satisfied with the size, I can shrink escaper and strip-css-comments is a couple of tiny functions

**Comment by infinnie** [comment]
PostCSS has a parser.
